/* eslint-disable prettier/prettier */
import React, {useCallback, useEffect, useState} from 'react';
import {Animated, StyleSheet, Text, TextInput, View} from 'react-native';
import {useDispatch, useSelector} from 'react-redux';

// components
import Dropdown from '../../../../components/DropDown';
import SamakanDataWaliDenganAyahAtauIbu from '../components/SamakanDataWaliDenganAyahAtauIbu';

// utils
import {windowWidth} from '../../../../utils';

// reducers
import {getProfilSaya} from '../../../../redux/reducer/SISWA/profilSaya';

// enum schema
import {
  jenisKelaminEnum,
  agamaEnum,
  kewarganegaraanEnum,
  pendidikanEnum,
  jenisTinggalEnum,
  apakahYatimPiatuEnum,
  apakahMasihHidupEnum,
} from '../validationSchema/profilSchema';

export default function useProfilSayaSiswa({flatlistRef}) {
  const dispatch = useDispatch();
  const {authSiswa = {}} = useSelector(state => state.authSiswa) || {};

  useEffect(() => {
    if (authSiswa?.data?.token?.length > 0) {
      dispatch(getProfilSaya({token: authSiswa?.data?.token}));
    }
  }, [authSiswa]);
  const [state, updateState] = React.useState();
  const forceUpdate = React.useCallback(() => updateState({}), []);

  const {profilSaya = {}, isLoadingUpdateProfilSaya = false} = useSelector(state => state.profilSayaSiswa) || {};
  const {
    nama,
    nik,
    nisn,
    jenis_kelamin,
    tempat_lahir,
    tanggal_lahir,
    alamat,
    nomor_wa,
    url_foto,
    tahun_masuk,
    nama_panggilan,
    agama,
    kewarganegaraan,
    anak_ke,
    jumlah_saudara_kandung,
    jumlah_saudara_tiri,
    jumlah_saudara_angkat,
    yatim_piatu,
    bahasa_seharihari,
    jenis_tinggal,
    jarak_rumah_kesekolah,
    golongan_darah,
    riwayat_penyakit,
    kelainan_jasmani,
    tinggi_badan,
    berat_badan,
    lulusan_dari_sekolah,
    tanggal_dan_nomor_sttb_sekolah_sebelumnya,
    lama_belajar_sekolah_sebelumnya,
    pindahan_dari_sekolah,
    alasan_pindah_sekolah,
    diterima_dikelas,
    diterima_pada_program,
    tanggal_diterima,
    ayah_nama,
    ayah_tempat_lahir,
    ayah_tanggal_lahir,
    ayah_agama,
    ayah_kewarganegaraan,
    ayah_pendidikan,
    ayah_pekerjaan,
    ayah_penghasilan,
    ayah_alamat,
    ayah_nomor_telepon,
    ayah_masih_hidup,
    ibu_nama,
    ibu_tempat_lahir,
    ibu_tanggal_lahir,
    ibu_agama,
    ibu_kewarganegaraan,
    ibu_pendidikan,
    ibu_pekerjaan,
    ibu_penghasilan,
    ibu_alamat,
    ibu_nomor_telepon,
    ibu_masih_hidup,
    wali_nama,
    wali_tempat_lahir,
    wali_tanggal_lahir,
    wali_agama,
    wali_kewarganegaraan,
    wali_pendidikan,
    wali_pekerjaan,
    wali_penghasilan,
    wali_alamat,
    wali_nomor_telepon,
    hobi_kesenian,
    hobi_olahraga,
    hobi_kemasyarakatan,
    hobi_lainlain,
    tinggal_meninggalkan_sekolah,
    alasan_meninggalkan_sekolah,
    tahun_tamat_belajar,
    nomor_sttb,
    melanjutkan_di,
    tanggal_mulai_beker,
    nama_instansi_tempat_bekerja,
    penghasilan,
  } = profilSaya?.siswa || {};

  const renderItem = useCallback(
    ({item, index}) => (
      <>
        <Text style={styles.inputTitle}>
          {item?.title}
          {item?.required && <Text style={styles.required}>{' '}*</Text>}
        </Text>
        {item?.inputType === 'textinput' ? (
          <TextInput
          placeholder={item?.placeholder}
          placeholderTextColor="grey"
          value={item.value}
          onChangeText={text => {
            item.onChangeText(
              {
                text: item?.keyboardType === 'numeric' ?
                      text.replace(/[^0-9]/g, '')
                      : text, keys: item?.keys,
              }
            );
          }}
          keyboardType={item?.keyboardType}
          style={[
            styles.input,
            item?.error?.length > 0 && styles.inputError,
          ]}
          editable={item?.editable}
          multiline={item?.multiline}
        />
        ) : (
          <Dropdown
            list={item?.list}
            type={item?.inputType || ''}
            selectedValue={item?.value}
            setValue={text => {
              item.onChangeText(
                {
                  text: item?.keyboardType === 'numeric' ?
                        text.replace(/[^0-9]/g, '')
                        : text, keys: item?.keys,
                }
              );
            }}
            controlledDate={false}
            selectedDate={item?.value}
            setSelectedDate={text => item.onChangeText({text, keys: item?.keys})}
            placeholder={item?.placeholder}
          />
        )}
        {item?.error?.length > 0 && (
          <Text style={styles.errorLabel}>* {item?.error}</Text>
        )}
      </>
    ),
    [],
  );

  const onChangeText = useCallback(({text, keys}) => {
    setTabSlides(prev => {
      return prev?.map(item => ({
        ...item,
        WrapperProps: {
          ...item?.WrapperProps,
          data: item?.WrapperProps?.data?.map?.(v =>
            v?.keys === keys
              ? {...v, value: text, error: ''}
              : v,
          ),
        },
      }));
    });
  }, [setTabSlides]);

  const samakanDenganAyahAtauIbu = useCallback((options = 'Ayah Kandung') => {
    setTabSlides(prev => {
      let dataAyahAtauIbu = prev?.find?.(item => item?.key === options)?.WrapperProps?.data;
      if (Array.isArray(dataAyahAtauIbu)) {
        const dataAyahAtauIbu_ToDataWali = dataAyahAtauIbu?.filter(item => item?.keys !== 'ayah_masih_hidup')?.map(item => ({
          ...item,
        belongTo: 'Wali',
        keys: item?.keys?.replace(options === 'Ayah Kandung' ? 'ayah_' : 'ibu_', 'wali_'),
        title: item?.title?.replace(options === 'Ayah Kandung' ? 'Nama Ayah' : 'Nama Ibu', 'Nama Wali'),
        }));
        return prev?.map(item => {
          if (item?.key === 'Wali') {
            return ({...item, WrapperProps: {
              ...item.WrapperProps,
              data: dataAyahAtauIbu_ToDataWali?.length > 0 ? dataAyahAtauIbu_ToDataWali : item?.data,
            }});
          } else {
            return item;
          }
        });
      } else {
        return prev;
      }
    });
  }, [setTabSlides]);

  const [tabSlides, setTabSlides] = useState(
    [
      {
        key: 'Data Siswa',
        title: 'Data Siswa',
        Wrapper: Animated.FlatList,
        WrapperProps: {
          ref: ref => {
            flatlistRef['Data Siswa'] = ref;
          },
          decelerationRate: 0.85,
          data: [
            {
              title: 'Nama Lengkap',
              value: nama,
              keys: 'nama',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: false,
              required: true,
              multiline: false,
              error: '',
              belongTo: 'Data Siswa',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'Nama Panggilan',
              value: nama_panggilan,
              keys: 'nama_panggilan',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Data Siswa',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'NIK',
              value: nik,
              keys: 'nik',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: false,
              required: true,
              multiline: false,
              error: '',
              belongTo: 'Data Siswa',
              keyboardType: 'numeric',
              inputType: 'textinput',
            },
            {
              title: 'NISN',
              value: nisn,
              keys: 'nisn',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: false,
              required: true,
              multiline: false,
              error: '',
              belongTo: 'Data Siswa',
              keyboardType: 'numeric',
              inputType: 'textinput',
            },
            {
              title: 'Password',
              value: '',
              keys: 'password',
              onChangeText,
              placeholder: '******',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Data Siswa',
              keyboardType: 'numeric',
              inputType: 'textinput',
            },
            {
              title: 'Jenis Kelamin',
              value: jenis_kelamin,
              keys: 'jenis_kelamin',
              onChangeText,
              placeholder: '- Jenis Kelamin -',
              editable: true,
              required: true,
              multiline: false,
              error: '',
              belongTo: 'Data Siswa',
              keyboardType: 'default',
              inputType: 'dropdown',
              list: jenisKelaminEnum,
            },
            {
              title: 'Tempat Lahir',
              value: tempat_lahir,
              keys: 'tempat_lahir',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: true,
              multiline: false,
              error: '',
              belongTo: 'Data Siswa',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'Tanggal Lahir',
              value: tanggal_lahir,
              keys: 'tanggal_lahir',
              onChangeText,
              placeholder: '- Pilih tanggal -',
              editable: true,
              required: true,
              multiline: false,
              error: '',
              belongTo: 'Data Siswa',
              keyboardType: 'default',
              inputType: 'date',
            },
            {
              title: 'Agama',
              value: agama,
              keys: 'agama',
              onChangeText,
              placeholder: '- Pilih Agama -',
              editable: true,
              required: true,
              multiline: false,
              error: '',
              belongTo: 'Data Siswa',
              keyboardType: 'default',
              inputType: 'dropdown',
              list: agamaEnum,
            },
            {
              title: 'Kewarganegaraan',
              value: kewarganegaraan,
              keys: 'kewarganegaraan',
              onChangeText,
              placeholder: '- Pilih Kewarganegaraan -',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Data Siswa',
              keyboardType: 'default',
              inputType: 'dropdown',
              list: kewarganegaraanEnum,
            },
          ],
          renderItem,
          style: {paddingHorizontal: '6%'},
          keyExtractor: (_item, index) => index,
          removeClippedSubviews: false,
        },
      },
      {
        key: 'Kegemaran Siswa',
        title: 'Kegemaran Siswa',
        Wrapper: Animated.FlatList,
        WrapperProps: {
          ref: ref => {
            flatlistRef['Kegemaran Siswa'] = ref;
          },
          decelerationRate: 0.85,
          data: [
            {
              title: 'Kesenian',
              value: hobi_kesenian,
              keys: 'hobi_kesenian',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Kegemaran Siswa',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'Olahraga',
              value: hobi_olahraga,
              keys: 'hobi_olahraga',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Kegemaran Siswa',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'Kemasyarakatan/Organisasi',
              value: hobi_kemasyarakatan,
              keys: 'hobi_kemasyarakatan',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Kegemaran Siswa',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'Lain-lain',
              value: hobi_lainlain,
              keys: 'hobi_lainlain',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Kegemaran Siswa',
              keyboardType: 'default',
              inputType: 'textinput',
            },
          ],
          renderItem,
          style: {paddingHorizontal: '6%'},
          keyExtractor: (_item, index) => index,
          removeClippedSubviews: false,
        },
      },
      {
        key: 'Tempat Tinggal',
        title: 'Tempat Tinggal',
        Wrapper: Animated.FlatList,
        WrapperProps: {
          ref: ref => {
            flatlistRef['Tempat Tinggal'] = ref;
          },
          decelerationRate: 0.85,
          data: [
            {
              title: 'Alamat',
              value: alamat,
              keys: 'alamat',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: true,
              error: '',
              belongTo: 'Tempat Tinggal',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'Nomor WA',
              value: nomor_wa,
              keys: 'nomor_wa',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Tempat Tinggal',
              keyboardType: 'numeric',
              inputType: 'textinput',
            },
            {
              title: 'Jenis Tinggal',
              value: jenis_tinggal,
              keys: 'jenis_tinggal',
              onChangeText,
              placeholder: '- Pilih Jenis Tinggal -',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Tempat Tinggal',
              keyboardType: 'default',
              inputType: 'dropdown',
              list: jenisTinggalEnum,
            },
            {
              title: 'Jarak tempat tinggal ke sekolah (KM)',
              value: jarak_rumah_kesekolah,
              keys: 'jarak_rumah_kesekolah',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Tempat Tinggal',
              keyboardType: 'numeric',
              inputType: 'textinput',
            },
          ],
          renderItem,
          style: {paddingHorizontal: '6%'},
          keyExtractor: (_item, index) => index,
          removeClippedSubviews: false,
        },
      },
      {
        key: 'Kesehatan',
        title: 'Kesehatan',
        Wrapper: Animated.FlatList,
        WrapperProps: {
          ref: ref => {
            flatlistRef.Kesehatan = ref;
          },
          decelerationRate: 0.85,
          data: [
            {
              title: 'Golongan Darah',
              value: golongan_darah,
              keys: 'golongan_darah',
              onChangeText,
              placeholder: '- Pilih Golongan Darah -',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Kesehatan',
              keyboardType: 'default',
              inputType: 'dropdown',
              list: ['A', 'B', 'AB', 'O'],
            },
            {
              title: 'Penyakit yang pernah diderita',
              value: riwayat_penyakit,
              keys: 'riwayat_penyakit',
              onChangeText,
              placeholder: 'TBC, Cacar, Malaria dan lain-lain',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Kesehatan',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'Kelainan Jasmani',
              value: kelainan_jasmani,
              keys: 'kelainan_jasmani',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Kesehatan',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'Tinggi Badan (cm)',
              value: tinggi_badan,
              keys: 'tinggi_badan',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Kesehatan',
              keyboardType: 'numeric',
              inputType: 'textinput',
            },
            {
              title: 'Berat Badan (kg)',
              value: berat_badan,
              keys: 'berat_badan',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Kesehatan',
              keyboardType: 'numeric',
              inputType: 'textinput',
            },
          ],
          renderItem,
          style: {paddingHorizontal: '6%'},
          keyExtractor: (_item, index) => index,
          removeClippedSubviews: false,
        },
      },
      {
        key: 'Dalam Keluarga',
        title: 'Dalam Keluarga',
        Wrapper: Animated.FlatList,
        WrapperProps: {
          ref: ref => {
            flatlistRef['Dalam Keluarga'] = ref;
          },
          decelerationRate: 0.85,
          data: [
            {
              title: 'Anak Ke',
              value: anak_ke,
              keys: 'anak_ke',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Dalam Keluarga',
              keyboardType: 'numeric',
              inputType: 'textinput',
            },
            {
              title: 'Jumlah Saudara Kandung',
              value: jumlah_saudara_kandung,
              keys: 'jumlah_saudara_kandung',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Dalam Keluarga',
              keyboardType: 'numeric',
              inputType: 'textinput',
            },
            {
              title: 'Jumlah Saudara Tiri',
              value: jumlah_saudara_tiri,
              keys: 'jumlah_saudara_tiri',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Dalam Keluarga',
              keyboardType: 'numeric',
              inputType: 'textinput',
            },
            {
              title: 'Jumlah Saudara Angkat',
              value: jumlah_saudara_angkat,
              keys: 'jumlah_saudara_angkat',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Dalam Keluarga',
              keyboardType: 'numeric',
              inputType: 'textinput',
            },
            {
              title: 'Anak Yatim/Piatu/Yatim Piatu',
              value: yatim_piatu,
              keys: 'yatim_piatu',
              onChangeText,
              placeholder: '- Pilih Anak Yatim/Piatu/Yatim Piatu -',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Dalam Keluarga',
              keyboardType: 'default',
              inputType: 'dropdown',
              list: apakahYatimPiatuEnum,
            },
            {
              title: 'Bahasa Sehari-hari dalam Keluarga',
              value: bahasa_seharihari,
              keys: 'bahasa_seharihari',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Dalam Keluarga',
              keyboardType: 'default',
              inputType: 'textinput',
            },
          ],
          renderItem,
          style: {paddingHorizontal: '6%'},
          keyExtractor: (_item, index) => index,
          removeClippedSubviews: false,
        },
      },
      {
        key: 'Pendidikan Sebelumnya',
        title: 'Pendidikan Sebelumnya',
        Wrapper: Animated.FlatList,
        WrapperProps: {
          ref: ref => {
            flatlistRef['Pendidikan Sebelumnya'] = ref;
          },
          decelerationRate: 0.85,
          data: [
            {
              title: 'Lulusan Dari Sekolah',
              value: lulusan_dari_sekolah,
              keys: 'lulusan_dari_sekolah',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Pendidikan Sebelumnya',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'Tanggal dan Nomor STTB Sekolah Sebelumnya',
              value: tanggal_dan_nomor_sttb_sekolah_sebelumnya,
              keys: 'tanggal_dan_nomor_sttb_sekolah_sebelumnya',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Pendidikan Sebelumnya',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'Jumlah Saudara Tiri',
              value: jumlah_saudara_tiri,
              keys: 'jumlah_saudara_tiri',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Pendidikan Sebelumnya',
              keyboardType: 'numeric',
              inputType: 'textinput',
            },
            {
              title: 'Lama Belajar Di Sekolah Sebelumnya',
              value: lama_belajar_sekolah_sebelumnya,
              keys: 'lama_belajar_sekolah_sebelumnya',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Pendidikan Sebelumnya',
              keyboardType: 'default',
              inputType: 'textinput',
            },
          ],
          renderItem,
          style: {paddingHorizontal: '6%'},
          keyExtractor: (_item, index) => index,
          removeClippedSubviews: false,
        },
      },
      {
        key: 'Pindahan',
        title: 'Pindahan',
        Wrapper: Animated.FlatList,
        WrapperProps: {
          ref: ref => {
            flatlistRef.Pindahan = ref;
          },
          decelerationRate: 0.85,
          data: [
            {
              title: 'Pindahan Dari Sekolah',
              value: pindahan_dari_sekolah,
              keys: 'pindahan_dari_sekolah',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Pindahan',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'Alasan Pindah Sekolah',
              value: alasan_pindah_sekolah,
              keys: 'alasan_pindah_sekolah',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Pindahan',
              keyboardType: 'default',
              inputType: 'textinput',
            },
          ],
          renderItem,
          style: {paddingHorizontal: '6%'},
          keyExtractor: (_item, index) => index,
          removeClippedSubviews: false,
        },
      },
      {
        key: 'Diterima Disekolah ini',
        title: 'Diterima Disekolah ini',
        Wrapper: Animated.FlatList,
        WrapperProps: {
          ref: ref => {
            flatlistRef['Diterima Disekolah ini'] = ref;
          },
          decelerationRate: 0.85,
          data: [
            {
              title: 'Diterima Di Kelas',
              value: diterima_dikelas,
              keys: 'diterima_dikelas',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Diterima Disekolah ini',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'Diterima Pada Program',
              value: diterima_pada_program,
              keys: 'diterima_pada_program',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Diterima Disekolah ini',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'Tanggal Diterima',
              value: tanggal_diterima,
              keys: 'tanggal_diterima',
              onChangeText,
              placeholder: '- Pilih Tanggal Diterima -',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Diterima Disekolah ini',
              keyboardType: 'default',
              inputType: 'date',
            },
          ],
          renderItem,
          style: {paddingHorizontal: '6%'},
          keyExtractor: (_item, index) => index,
          removeClippedSubviews: false,
        },
      },
      {
        key: 'Ayah Kandung',
        title: 'Ayah Kandung',
        Wrapper: Animated.FlatList,
        WrapperProps: {
          ref: ref => {
            flatlistRef['Ayah Kandung'] = ref;
          },
          decelerationRate: 0.85,
          data: [
            {
              title: 'Nama Ayah',
              value: ayah_nama,
              keys: 'ayah_nama',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Ayah Kandung',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'Tempat Lahir',
              value: ayah_tempat_lahir,
              keys: 'ayah_tempat_lahir',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Ayah Kandung',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'Tanggal Lahir',
              value: ayah_tanggal_lahir,
              keys: 'ayah_tanggal_lahir',
              onChangeText,
              placeholder: '- Pilih Tanggal Lahir -',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Ayah Kandung',
              keyboardType: 'default',
              inputType: 'date',
            },
            {
              title: 'Agama',
              value: ayah_agama,
              keys: 'ayah_agama',
              onChangeText,
              placeholder: '- Pilih Agama -',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Ayah Kandung',
              keyboardType: 'default',
              inputType: 'dropdown',
              list: agamaEnum,
            },
            {
              title: 'Kewarganegaraan',
              value: ayah_kewarganegaraan,
              keys: 'ayah_kewarganegaraan',
              onChangeText,
              placeholder: '- Pilih Kewarganegaraan -',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Ayah Kandung',
              keyboardType: 'default',
              inputType: 'dropdown',
              list: kewarganegaraanEnum,
            },
            {
              title: 'Pendidikan',
              value: ayah_pendidikan,
              keys: 'ayah_pendidikan',
              onChangeText,
              placeholder: '- Pilih Pendidikan -',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Ayah Kandung',
              keyboardType: 'default',
              inputType: 'dropdown',
              list: pendidikanEnum,
            },
            {
              title: 'Penghasilan Perbulan',
              value: ayah_penghasilan,
              keys: 'ayah_penghasilan',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Ayah Kandung',
              keyboardType: 'numeric',
              inputType: 'textinput',
            },
            {
              title: 'Alamat',
              value: ayah_alamat,
              keys: 'ayah_alamat',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Ayah Kandung',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'Nomor Telepon',
              value: ayah_nomor_telepon,
              keys: 'ayah_nomor_telepon',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Ayah Kandung',
              keyboardType: 'numeric',
              inputType: 'textinput',
            },
            {
              title: 'Masih Hidup/Meninggal',
              value: ayah_masih_hidup,
              keys: 'ayah_masih_hidup',
              onChangeText,
              placeholder: '- Pilih Masih Hidup/Meninggal -',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Ayah Kandung',
              keyboardType: 'default',
              inputType: 'dropdown',
              list: apakahMasihHidupEnum,
            },
          ],
          renderItem,
          style: {paddingHorizontal: '6%'},
          keyExtractor: (_item, index) => index,
          removeClippedSubviews: false,
        },
      },
      {
        key: 'Ibu Kandung',
        title: 'Ibu Kandung',
        Wrapper: Animated.FlatList,
        WrapperProps: {
          ref: ref => {
            flatlistRef['Ibu Kandung'] = ref;
          },
          decelerationRate: 0.85,
          data: [
            {
              title: 'Nama Ibu',
              value: ibu_nama,
              keys: 'ibu_nama',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Ibu Kandung',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'Tempat Lahir',
              value: ibu_tempat_lahir,
              keys: 'ibu_tempat_lahir',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Ibu Kandung',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'Tanggal Lahir',
              value: ibu_tanggal_lahir,
              keys: 'ibu_tanggal_lahir',
              onChangeText,
              placeholder: '- Pilih Tanggal Lahir -',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Ibu Kandung',
              keyboardType: 'default',
              inputType: 'date',
            },
            {
              title: 'Agama',
              value: ibu_agama,
              keys: 'ibu_agama',
              onChangeText,
              placeholder: '- Pilih Agama -',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Ibu Kandung',
              keyboardType: 'default',
              inputType: 'dropdown',
              list: agamaEnum,
            },
            {
              title: 'Kewarganegaraan',
              value: ibu_kewarganegaraan,
              keys: 'ibu_kewarganegaraan',
              onChangeText,
              placeholder: '- Pilih Kewarganegaraan -',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Ibu Kandung',
              keyboardType: 'default',
              inputType: 'dropdown',
              list: kewarganegaraanEnum,
            },
            {
              title: 'Pendidikan',
              value: ibu_pendidikan,
              keys: 'ibu_pendidikan',
              onChangeText,
              placeholder: '- Pilih Pendidikan -',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Ibu Kandung',
              keyboardType: 'default',
              inputType: 'dropdown',
              list: pendidikanEnum,
            },
            {
              title: 'Penghasilan Perbulan',
              value: ibu_penghasilan,
              keys: 'ibu_penghasilan',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Ibu Kandung',
              keyboardType: 'numeric',
              inputType: 'textinput',
            },
            {
              title: 'Alamat',
              value: ibu_alamat,
              keys: 'ibu_alamat',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Ibu Kandung',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'Nomor Telepon',
              value: ibu_nomor_telepon,
              keys: 'ibu_nomor_telepon',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Ibu Kandung',
              keyboardType: 'numeric',
              inputType: 'textinput',
            },
            {
              title: 'Masih Hidup/Meninggal',
              value: ibu_masih_hidup,
              keys: 'ibu_masih_hidup',
              onChangeText,
              placeholder: '- Pilih Masih Hidup/Meninggal -',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Ibu Kandung',
              keyboardType: 'default',
              inputType: 'dropdown',
              list: apakahMasihHidupEnum,
            },
          ],
          renderItem,
          style: {paddingHorizontal: '6%'},
          keyExtractor: (_item, index) => index,
          removeClippedSubviews: false,
        },
      },
      {
        key: 'Wali',
        title: 'Wali',
        Wrapper: Animated.FlatList,
        WrapperProps: {
          ref: ref => {
            flatlistRef.Wali = ref;
          },
          ListHeaderComponent: <SamakanDataWaliDenganAyahAtauIbu samakanDenganAyahAtauIbu={samakanDenganAyahAtauIbu} />,
          decelerationRate: 0.85,
          data: [
            {
              title: 'Nama Wali',
              value: wali_nama,
              keys: 'wali_nama',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Wali',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'Tempat Lahir',
              value: wali_tempat_lahir,
              keys: 'wali_tempat_lahir',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Wali',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'Tanggal Lahir',
              value: wali_tanggal_lahir,
              keys: 'wali_tanggal_lahir',
              onChangeText,
              placeholder: '- Pilih Tanggal Lahir -',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Wali',
              keyboardType: 'default',
              inputType: 'date',
            },
            {
              title: 'Agama',
              value: wali_agama,
              keys: 'wali_agama',
              onChangeText,
              placeholder: '- Pilih Agama -',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Wali',
              keyboardType: 'default',
              inputType: 'dropdown',
              list: agamaEnum,
            },
            {
              title: 'Kewarganegaraan',
              value: wali_kewarganegaraan,
              keys: 'wali_kewarganegaraan',
              onChangeText,
              placeholder: '- Pilih Kewarganegaraan -',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Wali',
              keyboardType: 'default',
              inputType: 'dropdown',
              list: kewarganegaraanEnum,
            },
            {
              title: 'Pendidikan',
              value: wali_pendidikan,
              keys: 'wali_pendidikan',
              onChangeText,
              placeholder: '- Pilih Pendidikan -',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Wali',
              keyboardType: 'default',
              inputType: 'dropdown',
              list: pendidikanEnum,
            },
            {
              title: 'Penghasilan Perbulan',
              value: wali_penghasilan,
              keys: 'wali_penghasilan',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Wali',
              keyboardType: 'numeric',
              inputType: 'textinput',
            },
            {
              title: 'Alamat',
              value: wali_alamat,
              keys: 'wali_alamat',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Wali',
              keyboardType: 'default',
              inputType: 'textinput',
            },
            {
              title: 'Nomor Telepon',
              value: wali_nomor_telepon,
              keys: 'wali_nomor_telepon',
              onChangeText,
              placeholder: 'Belum diisi',
              editable: true,
              required: false,
              multiline: false,
              error: '',
              belongTo: 'Wali',
              keyboardType: 'numeric',
              inputType: 'textinput',
            },
          ],
          renderItem,
          style: {paddingHorizontal: '6%'},
          keyExtractor: (_item, index) => index,
          removeClippedSubviews: false,
        },
      },
    ]);

  return {isLoadingUpdateProfilSaya, tabSlides, setTabSlides, onChangeText, url_foto};
}

const styles = StyleSheet.create({
  inputTitle: {
    fontSize: windowWidth * 0.04,
    color: 'black',
    fontFamily: 'OpenSans-SemiBold',
  },
  required: {
    color: 'red',
    fontFamily: 'OpenSans-Regular',
    fontSize: windowWidth * 0.036,
  },
  errorLabel: {
    color: 'red',
    fontFamily: 'OpenSans-Italic',
    fontSize: windowWidth * 0.034,
    marginTop: '-4%',
    marginBottom: '2%',
    marginLeft: '2%',
  },
  input: {
    fontSize: windowWidth * 0.04,
    color: 'black',
    width: '100%',
    borderRadius: windowWidth * 0.02,
    marginTop: '3%',
    paddingHorizontal: '3%',
    paddingVertical: '2.5%',
    fontFamily: 'OpenSans-Regular',
    marginBottom: '6%',
    borderWidth: 0.8,
  },
  inputFocus: {
    borderWidth: 1,
    borderColor: '#0099e5',
  },
  inputError: {
    borderWidth: 1,
    borderColor: 'red',
  },
});
